image: node:latest

stages:
  - test

cache:
  paths:
    - node_modules/
    # - .yarn

before_script:
  - apt-get update -qq && apt-get install

test:
  stage: test
  before_script:
    # - yarn config set cache-folder .yarn
    - yarn
  script:
    - yarn run build:ci
    - yarn test
