image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - node_modules/
    - .yarn

before_script:
  - apt-get update -qq && apt-get install

Build:
  stage: build
  before_script:
    - yarn config set cache-folder .yarn
    - yarn
  script:
    - yarn run build
  artifacts:
    paths:
      - node_modules/

Test:
  stage: test
  before_script:
    - yarn config set cache-folder .yarn
    - yarn
  script:
    - npx lerna exec -- ls node_modules/
    - npx lerna exec -- ls node_modules/.bin
    - yarn test
